export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";

export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

export const USER_VERIFY_FAIL = "USER_VERIFY_FAIL";
export const USER_VERIFY_REQUEST = "USER_VERIFY_REQUEST";
export const USER_VERIFY_SUCCESS = "USER_VERIFY_SUCCESS";

export const GET_PACKAGE_REQUEST = "GET_PACKAGE_REQUEST";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_PACKAGE_FAIL = "GET_PACKAGE_FAIL";
